# Generated by Django 4.2.10 on 2024-02-11 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="link",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
