# Generated by Django 4.2.10 on 2024-02-11 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_playlist_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("band", models.CharField(max_length=128)),
                (
                    "dance",
                    models.CharField(
                        choices=[
                            ("mazurka", "Mazurka"),
                            ("scottish", "Scottish"),
                            ("waltz_3", "Waltz in 3"),
                            ("waltz_5", "Waltz in 5"),
                            ("waltz_7", "Waltz in 7"),
                        ],
                        max_length=16,
                    ),
                ),
            ],
        ),
    ]
