# Generated by Django 4.2.10 on 2024-02-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0003_song"),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
