# Generated by Django 4.2.10 on 2024-02-11 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0004_song_visible"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="platform",
            field=models.CharField(
                choices=[
                    ("spotify", "Spotify"),
                    ("soundcloud", "SoundCloud"),
                    ("youtube", "Youtube"),
                    ("apple_music", "Apple Music"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="song",
            name="dance",
            field=models.CharField(
                choices=[
                    ("mazurka", "Mazurka"),
                    ("scottish", "Scottish"),
                    ("waltz_3", "Waltz in 3"),
                    ("waltz_5", "Waltz in 5"),
                    ("waltz_7", "Waltz in 7"),
                    ("jig", "Jig / Chappeloise"),
                    ("cercle", "Cercle Circassien"),
                ],
                max_length=16,
            ),
        ),
    ]
