# Generated by Django 4.2.10 on 2024-02-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0005_alter_playlist_platform_alter_song_dance"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="platform_id",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
