# Generated by Django 4.2.10 on 2024-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_course_festival"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[("festival", "Festival"), ("course", "Course")], default="festival", max_length=16
            ),
            preserve_default=False,
        ),
    ]
