# Generated by Django 4.2.10 on 2024-02-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
