# Generated by Django 4.2.10 on 2024-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_event_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="address",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[("festival", "Festival"), ("course", "Course")], default="festival", max_length=16
            ),
        ),
    ]
