# Generated by Django 4.2.10 on 2024-02-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0008_alter_event_address_alter_event_lattitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tagline",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
