# Generated by Django 4.2.10 on 2024-02-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0009_event_tagline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bal",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("events.event",),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[("festival", "Festival"), ("course", "Course"), ("bal", "Bal")],
                default="festival",
                max_length=16,
            ),
        ),
    ]
