# Generated by Django 4.2.10 on 2024-02-12 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0010_bal_alter_event_event_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bal",
        ),
        migrations.CreateModel(
            name="Ball",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("events.event",),
        ),
    ]
