# Generated by Django 4.2.10 on 2024-02-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0012_alter_event_country_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="folkbende_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
