# Generated by Django 4.2.10 on 2024-02-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0013_event_folkbende_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventDate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="end_timestamp",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_timestamp",
            field=models.TimeField(),
        ),
        migrations.AddField(
            model_name="event",
            name="dates",
            field=models.ManyToManyField(to="events.eventdate"),
        ),
    ]
