# Generated by Django 4.2.10 on 2024-02-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0014_eventdate_alter_event_end_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="schedule",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="tagline",
            field=models.TextField(blank=True),
        ),
    ]
