# Generated by Django 4.2.10 on 2024-02-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0015_event_schedule_alter_event_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="event",
            name="pricing",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="schedule",
            field=models.TextField(blank=True, help_text="Schedule, with e.g. the bands that are playing"),
        ),
    ]
