# Generated by Django 4.2.10 on 2024-02-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0016_event_city_event_pricing_alter_event_schedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="organizer",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
