# Generated by Django 4.2.10 on 2024-02-15 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0018_event_banner_image_event_poster_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
    ]
