# Generated by Django 4.2.10 on 2024-02-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0019_remove_event_image"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["event_type", "visible"], name="events_even_event_t_b97e37_idx"),
        ),
    ]
