# Generated by Django 4.2.10 on 2024-02-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0020_event_events_even_event_t_b97e37_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="balfolknl_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
