# Generated by Django 4.2.10 on 2024-02-18 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0022_remove_event_tagline"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="ending_datetime",
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 18, 15, 12, 11, 638502)),
            preserve_default=False,
        ),
    ]
