# Generated by Django 4.2.10 on 2024-02-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0023_event_ending_datetime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="ending_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
