# Generated by Django 4.2.10 on 2024-02-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0024_alter_event_ending_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="starting_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
