# Generated by Django 4.2.10 on 2024-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0025_event_starting_datetime"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.CharField(
                choices=[("folkbalbende", "FolkBalBende"), ("balfolk.nl", "Balfolk.nl"), ("folkdance.page", "Folkdance.page"), ("website", "website")],
                default="website",
                max_length=24,
            ),
            preserve_default=False,
        ),
    ]
