# Generated by Django 4.2.10 on 2024-02-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0026_event_source"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["visible", "event_type"], name="events_even_visible_fbff36_idx"),
        ),
    ]
